import { createHash } from 'node:crypto';

// Super Productivity released evidence: release: v18.22.0
// commit: 88d533285170f8e4e483355f59ff6c03b1d385ff
// Full source bytes copied from the pinned commit. Tag/commit are provenance
// metadata; offline blob checks do not rediscover the upstream tag-to-commit chain.
export const RELEASED_V18_22_0 = {
  releaseTag: 'v18.22.0',
  commitSha: '88d533285170f8e4e483355f59ff6c03b1d385ff',
  sources: {
    'packages/shared-schema/src/schema-version.ts': {
      blobSha: '7f5a6d2697dffb938d2582fdf2ee8d195bf63a3c',
      source: [
        '/**',
        ' * Current schema version for all operations and state snapshots.',
        ' *',
        ' * DO NOT BUMP THIS LIGHTLY — default is to NOT bump. A bump is a near-one-way',
        ' * fence: it hard-blocks every not-yet-updated post-v18.14.0 client (frozen',
        ' * cursor) on the new ops, and it CANNOT be reverted once any op carries the new',
        ' * version — a reverted client hard-blocks on the v(N+1) ops it already wrote and',
        ' * the USE_REMOTE recovery path throws on them. So a bump must earn its cost. If',
        ' * old clients can apply the op unmigrated, gate the new semantics on a payload',
        ' * marker / envelope (see LwwUpdatePayload in packages/sync-core) and LEAVE THIS',
        ' * CONSTANT ALONE. Only bump when a change genuinely requires it: a transforming',
        ' * migration (renamed/removed field, dropped op) or a semantic you must hard-fence',
        ' * off older clients. Cautionary example — v4 (#9009 project delete-wins) was',
        ' * bumped for a marker-only change old clients degrade on fine: it needed no bump,',
        ' * yet it now fences every lagging post-v18.14.0 client. Then, and only then,',
        ' * increment this BEFORE adding the new migration.',
        ' *',
        ' * BUMP POLICY — a bump does NOT protect the released fleet. Every released',
        ' * client from v17.0.0 through v18.14.0 tolerates ops up to schema 5 (its',
        ' * version 2 plus the old MAX_VERSION_SKIP band of 3) and applies them',
        ' * UNMIGRATED after one warning snack per session; at schema >= 6 it blocks,',
        ' * but still advances the server cursor, permanently skipping the blocked ops',
        ' * even after the user updates. Only post-v18.14.0 receivers block newer ops',
        ' * safely (cursor frozen). Therefore new op semantics must degrade gracefully on older',
        ' * clients (see the LwwUpdatePayload envelope pattern in packages/sync-core);',
        ' * a change old clients would MISAPPLY must not ship behind a bump alone.',
        ' *',
        ' * PRECONDITION for the next bump — the downgrade relabel (#8770): until a',
        ' * guard ships, every migration added here MUST be a no-op on already-migrated',
        ' * state, and the bump PR must say how downgraded clients are handled.',
        ' * Mechanism: A.7.11 Bump Policy item 3.',
        ' *',
        ' * Full policy: docs/sync-and-op-log/operation-log-architecture.md, A.7.11',
        ' * "Bump Policy".',
        ' */',
        'export const PROJECT_DELETE_WINS_SCHEMA_VERSION = 4;',
        'export const CURRENT_SCHEMA_VERSION = PROJECT_DELETE_WINS_SCHEMA_VERSION;',
        '',
        '/**',
        ' * Minimum schema version that this codebase can still handle.',
        ' * Operations below this version cannot be processed.',
        ' */',
        'export const MIN_SUPPORTED_SCHEMA_VERSION = 1;',
        '',
        '// NOTE: there is deliberately NO forward-compat band: any op from a NEWER',
        '// schema version is blocked outright (the client cannot know how to interpret',
        '// it), and the user is prompted to update the app.',
        '',
      ].join('\n'),
    },
    'src/app/op-log/persistence/schema-migration.service.ts': {
      blobSha: '6fc5d04a03eac4d658d32b845679de832d9e6ed5',
      source: [
        "import { Injectable } from '@angular/core';",
        "import { Operation, VectorClock } from '../core/operation.types';",
        "import { OpLog } from '../../core/log';",
        'import {',
        '  CURRENT_SCHEMA_VERSION as SHARED_CURRENT_SCHEMA_VERSION,',
        '  MIN_SUPPORTED_SCHEMA_VERSION as SHARED_MIN_SUPPORTED_SCHEMA_VERSION,',
        '  MIGRATIONS,',
        '  migrateState,',
        '  migrateOperation as sharedMigrateOperation,',
        '  stateNeedsMigration,',
        '  operationNeedsMigration as sharedOperationNeedsMigration,',
        '  validateMigrationRegistry,',
        '  type SchemaMigration,',
        '  type OperationLike,',
        "} from '@sp/shared-schema';",
        '',
        '// Re-export shared constants for backwards compatibility',
        'export const CURRENT_SCHEMA_VERSION = SHARED_CURRENT_SCHEMA_VERSION;',
        'export const MIN_SUPPORTED_SCHEMA_VERSION = SHARED_MIN_SUPPORTED_SCHEMA_VERSION;',
        '',
        '// Re-export types',
        'export type { SchemaMigration };',
        '',
        'export const getOperationSchemaVersion = (op: { schemaVersion?: unknown }): number => {',
        '  if (op.schemaVersion === undefined) {',
        '    return 1;',
        '  }',
        '  if (',
        "    typeof op.schemaVersion !== 'number' ||",
        '    !Number.isInteger(op.schemaVersion) ||',
        "    // Deliberately accepts 0 (unlike the server contract's min(1)): a parsed 0",
        '    // then fails the MIN_SUPPORTED_SCHEMA_VERSION comparison and surfaces as',
        '    // VERSION_UNSUPPORTED — a truthful message — instead of a generic',
        '    // migration-failure. Safety is identical either way.',
        '    op.schemaVersion < 0',
        '  ) {',
        '    throw new Error(',
        "      'Operation schemaVersion must be a non-negative integer when present.',",
        '    );',
        '  }',
        '  return op.schemaVersion;',
        '};',
        '',
        '/**',
        ' * Interface for state cache that may need migration.',
        ' */',
        'export interface MigratableStateCache {',
        '  state: unknown;',
        '  lastAppliedOpSeq: number;',
        '  vectorClock: VectorClock;',
        '  compactedAt: number;',
        '  schemaVersion?: number; // Optional for backward compatibility with old caches',
        '}',
        '',
        '/**',
        ' * Service responsible for migrating state cache snapshots and operations',
        ' * between schema versions.',
        ' *',
        ' * This is an Angular wrapper around the shared schema migration functions',
        ' * from @sp/shared-schema package.',
        ' *',
        " * When the application's state structure changes (e.g., new fields, renamed properties),",
        ' * migrations ensure old snapshots and operations can be upgraded to work with new code.',
        ' *',
        ' * Migration strategy for state (A.7.1):',
        ' * 1. Load snapshot from SUP_OPS',
        ' * 2. Check if schemaVersion < CURRENT_SCHEMA_VERSION',
        ' * 3. If so, run migrations sequentially until current version',
        ' * 4. Save migrated snapshot back to SUP_OPS',
        ' * 5. Continue with normal hydration',
        ' *',
        ' * Migration strategy for operations (A.7.13):',
        ' * 1. Load tail ops after snapshot',
        ' * 2. For each op where op.schemaVersion < CURRENT_SCHEMA_VERSION:',
        ' *    - Run migrateOperation() to transform payload',
        ' *    - Drop op if migration returns null',
        ' * 3. Apply migrated ops to migrated state',
        ' *',
        ' * @see docs/sync-and-op-log/operation-log-architecture.md A.7',
        ' */',
        "@Injectable({ providedIn: 'root' })",
        'export class SchemaMigrationService {',
        '  constructor() {',
        '    // Validate migration registry on startup (A.7.15)',
        '    this._validateMigrationRegistry();',
        '  }',
        '',
        '  /**',
        '   * Validates that all migrations with requiresOperationMigration=true',
        '   * have a migrateOperation function defined.',
        '   */',
        '  private _validateMigrationRegistry(): void {',
        '    const errors = validateMigrationRegistry();',
        '    if (errors.length > 0) {',
        '      throw new Error(',
        "        `SchemaMigrationService: Invalid migration registry:\\n${errors.join('\\n')}`,",
        '      );',
        '    }',
        '  }',
        '',
        '  /**',
        '   * Migrates a state cache to the current schema version if needed.',
        '   * Returns the migrated cache, or the original if no migration was needed.',
        '   * The result always carries the version the chain produced, which is what',
        '   * makes it safe to persist via `saveStateCache()` (#8770).',
        '   */',
        '  migrateStateIfNeeded(',
        '    cache: MigratableStateCache,',
        '  ): MigratableStateCache & { schemaVersion: number } {',
        "    // Handle old caches that don't have schemaVersion",
        '    const currentVersion = cache.schemaVersion ?? 1;',
        '',
        '    if (currentVersion >= CURRENT_SCHEMA_VERSION) {',
        '      // Already at current version',
        '      return {',
        '        ...cache,',
        '        schemaVersion: CURRENT_SCHEMA_VERSION,',
        '      };',
        '    }',
        '',
        '    OpLog.normal(',
        '      `SchemaMigrationService: Migrating state from v${currentVersion} to v${CURRENT_SCHEMA_VERSION}`,',
        '    );',
        '',
        '    const result = migrateState(cache.state, currentVersion, CURRENT_SCHEMA_VERSION);',
        '',
        '    if (!result.success) {',
        '      throw new Error(`SchemaMigrationService: ${result.error}`);',
        '    }',
        '',
        '    OpLog.normal(',
        '      `SchemaMigrationService: State migration complete. Now at v${CURRENT_SCHEMA_VERSION}`,',
        '    );',
        '',
        '    return {',
        '      ...cache,',
        '      state: result.data,',
        '      schemaVersion: CURRENT_SCHEMA_VERSION,',
        '    };',
        '  }',
        '',
        '  /**',
        '   * @deprecated Use migrateStateIfNeeded instead',
        '   */',
        '  migrateIfNeeded(cache: MigratableStateCache): MigratableStateCache {',
        '    return this.migrateStateIfNeeded(cache);',
        '  }',
        '',
        '  /**',
        '   * Migrates a single operation to the current schema version if needed.',
        '   * Returns null if the operation should be dropped (e.g., for removed features).',
        '   * Returns an array if the operation should be split into multiple operations.',
        '   *',
        '   * @param op - The operation to migrate',
        '   * @returns The migrated operation(s), or null if it should be dropped',
        '   */',
        '  migrateOperation(op: Operation): Operation | Operation[] | null {',
        '    const opVersion = getOperationSchemaVersion(op);',
        '',
        '    if (opVersion >= CURRENT_SCHEMA_VERSION) {',
        '      return op;',
        '    }',
        '',
        '    // Convert to OperationLike for the shared function',
        '    const opLike: OperationLike = {',
        '      id: op.id,',
        '      opType: op.opType,',
        '      entityType: op.entityType,',
        '      entityId: op.entityId,',
        '      entityIds: op.entityIds,',
        '      payload: op.payload,',
        '      schemaVersion: opVersion,',
        '    };',
        '',
        '    const result = sharedMigrateOperation(opLike, CURRENT_SCHEMA_VERSION);',
        '',
        '    if (!result.success) {',
        '      throw new Error(`SchemaMigrationService: ${result.error}`);',
        '    }',
        '',
        '    if (result.data === null || result.data === undefined) {',
        '      return null;',
        '    }',
        '',
        '    // Handle array result (operation was split into multiple)',
        '    if (Array.isArray(result.data)) {',
        '      return result.data.map((migratedOpLike) => ({',
        '        ...op,',
        '        id: migratedOpLike.id,',
        "        opType: migratedOpLike.opType as Operation['opType'],",
        "        entityType: migratedOpLike.entityType as Operation['entityType'],",
        '        entityId: migratedOpLike.entityId,',
        '        entityIds: migratedOpLike.entityIds,',
        '        payload: migratedOpLike.payload,',
        '        schemaVersion: migratedOpLike.schemaVersion,',
        '      }));',
        '    }',
        '',
        '    // Merge migrated fields back into the original operation',
        '    return {',
        '      ...op,',
        '      id: result.data.id,',
        "      opType: result.data.opType as Operation['opType'],",
        "      entityType: result.data.entityType as Operation['entityType'],",
        '      entityId: result.data.entityId,',
        '      entityIds: result.data.entityIds,',
        '      payload: result.data.payload,',
        '      schemaVersion: result.data.schemaVersion,',
        '    };',
        '  }',
        '',
        '  /**',
        '   * Migrates an array of operations, filtering out any that should be dropped.',
        '   * Handles operations that are split into multiple operations.',
        '   *',
        '   * @param ops - The operations to migrate',
        '   * @returns Array of migrated operations (dropped operations excluded)',
        '   */',
        '  migrateOperations(ops: Operation[]): Operation[] {',
        '    const migrated: Operation[] = [];',
        '',
        '    for (const op of ops) {',
        '      const migratedResult = this.migrateOperation(op);',
        '      if (migratedResult === null) {',
        '        OpLog.normal(',
        '          `SchemaMigrationService: Dropped operation ${op.id} (${op.actionType}) during migration`,',
        '        );',
        '      } else if (Array.isArray(migratedResult)) {',
        '        // Operation was split into multiple operations',
        '        migrated.push(...migratedResult);',
        '        OpLog.normal(',
        '          `SchemaMigrationService: Split operation ${op.id} into ${migratedResult.length} operations during migration`,',
        '        );',
        '      } else {',
        '        migrated.push(migratedResult);',
        '      }',
        '    }',
        '',
        '    return migrated;',
        '  }',
        '',
        '  /**',
        '   * Returns true if the cache needs migration.',
        '   */',
        '  needsMigration(cache: MigratableStateCache): boolean {',
        '    return stateNeedsMigration(cache.schemaVersion, CURRENT_SCHEMA_VERSION);',
        '  }',
        '',
        '  /**',
        '   * Returns true if the operation needs migration.',
        '   */',
        '  operationNeedsMigration(op: Operation): boolean {',
        '    const schemaVersion = getOperationSchemaVersion(op);',
        '    return sharedOperationNeedsMigration(',
        '      {',
        '        id: op.id,',
        '        opType: op.opType,',
        '        entityType: op.entityType,',
        '        payload: op.payload,',
        '        schemaVersion,',
        '      },',
        '      CURRENT_SCHEMA_VERSION,',
        '    );',
        '  }',
        '',
        '  /**',
        '   * Returns the current schema version.',
        '   */',
        '  getCurrentVersion(): number {',
        '    return CURRENT_SCHEMA_VERSION;',
        '  }',
        '',
        '  /**',
        '   * Returns registered migrations for a specific version range.',
        '   * If no range is provided, returns all migrations.',
        '   *',
        '   * @param fromVersion - The starting version (inclusive).',
        '   * @param toVersion - The ending version (inclusive).',
        '   * @returns Array of migrations within the specified range.',
        '   */',
        '  getMigrations(fromVersion?: number, toVersion?: number): readonly SchemaMigration[] {',
        '    if (fromVersion === undefined && toVersion === undefined) {',
        '      return MIGRATIONS;',
        '    }',
        '',
        '    return MIGRATIONS.filter((migration) => {',
        '      const isAfterFromVersion =',
        '        fromVersion === undefined || migration.fromVersion >= fromVersion;',
        '      const isBeforeToVersion =',
        '        toVersion === undefined || migration.toVersion <= toVersion;',
        '      return isAfterFromVersion && isBeforeToVersion;',
        '    });',
        '  }',
        '}',
        '',
      ].join('\n'),
    },
    'src/app/op-log/sync/remote-op-block.util.ts': {
      blobSha: '2834cf8c89a4fd64de443cb08d1aa8992eeda16f',
      source: [
        "import { CURRENT_SCHEMA_VERSION, SUPER_SYNC_IMPORT_REASONS } from '@sp/shared-schema';",
        "import { OpType, Operation } from '../core/operation.types';",
        'import {',
        '  getOperationSchemaVersion,',
        '  MIN_SUPPORTED_SCHEMA_VERSION,',
        "} from '../persistence/schema-migration.service';",
        '',
        'const KNOWN_OP_TYPES: ReadonlySet<string> = new Set<string>(Object.values(OpType));',
        'const KNOWN_IMPORT_REASONS: ReadonlySet<string> = new Set<string>(',
        '  SUPER_SYNC_IMPORT_REASONS,',
        ');',
        '',
        "export type UnknownOpVocabulary = 'opType' | 'syncImportReason';",
        '',
        '/**',
        ' * Names the vocabulary field of a remote op this client cannot interpret, or',
        ' * `null` when every value is known.',
        ' *',
        ' * The wire contract deliberately parses `opType` / `syncImportReason` as loose',
        " * strings (#8764) so a newer client's ops never wedge an older one at the",
        ' * transport layer. The receiver must therefore make the call per op: an',
        ' * unknown value means a newer client widened the vocabulary, and this client',
        ' * can neither apply the op (unknown semantics) nor skip it (silent loss).',
        ' */',
        'export const getUnknownOpVocabulary = (',
        "  op: Pick<Operation, 'opType' | 'syncImportReason'>,",
        '): UnknownOpVocabulary | null => {',
        '  // Only a PRESENT value can be unknown. Structural validity (opType is a',
        "  // required non-empty string) is the transport schema's job, not this one's.",
        '  if (isPresentUnknown(op.opType, KNOWN_OP_TYPES)) {',
        "    return 'opType';",
        '  }',
        '  if (isPresentUnknown(op.syncImportReason, KNOWN_IMPORT_REASONS)) {',
        "    return 'syncImportReason';",
        '  }',
        '  return null;',
        '};',
        '',
        'const isPresentUnknown = (value: unknown, known: ReadonlySet<string>): boolean =>',
        "  typeof value === 'string' && !known.has(value);",
        '',
        '/**',
        ' * Why a remote batch stops at an op it cannot terminally process. Every reason',
        ' * freezes the server cursor at the blocked op (see',
        ' * `RemoteOpsProcessingService.processRemoteOps`). `MIGRATION_FAILED` is only',
        ' * known after attempting the migration and is therefore not returned by',
        ' * {@link getRemoteOpBlockReason}.',
        ' */',
        'export type RemoteOpBlockReason =',
        "  | 'VERSION_UNSUPPORTED'",
        "  | 'VERSION_TOO_NEW'",
        "  | 'UNKNOWN_OP_VOCABULARY'",
        "  | 'INVALID_SCHEMA_VERSION'",
        "  | 'MIGRATION_FAILED';",
        '',
        '/**',
        ' * The ONE predicate for "this client cannot process this remote op", shared',
        ' * by the processing loop and every pre-processing step that must not act on',
        ' * (or prompt about) an op the loop will then refuse. Order matches the loop:',
        ' * schema-version checks first, vocabulary second.',
        ' */',
        'export const getRemoteOpBlockReason = (',
        "  op: Pick<Operation, 'opType' | 'syncImportReason'> & { schemaVersion?: unknown },",
        '  currentVersion: number,',
        "): Exclude<RemoteOpBlockReason, 'MIGRATION_FAILED'> | null => {",
        '  let opVersion: number;',
        '  try {',
        '    opVersion = getOperationSchemaVersion(op);',
        '  } catch {',
        "    return 'INVALID_SCHEMA_VERSION';",
        '  }',
        '  // Below minimum supported version: no migration path exists.',
        '  if (opVersion < MIN_SUPPORTED_SCHEMA_VERSION) {',
        "    return 'VERSION_UNSUPPORTED';",
        '  }',
        '  // Newer schema version: real migrations rename/split fields, so applying',
        '  // a future op verbatim corrupts state.',
        '  if (opVersion > currentVersion) {',
        "    return 'VERSION_TOO_NEW';",
        '  }',
        '  // Unknown opType / syncImportReason: a newer client widened the wire',
        '  // vocabulary without a schema bump (the default per the bump policy).',
        '  // Same treatment as VERSION_TOO_NEW — block, lossless, update-app UX —',
        '  // never skip: advancing the cursor past an op this client never',
        '  // understood is silent data loss.',
        '  if (getUnknownOpVocabulary(op) !== null) {',
        "    return 'UNKNOWN_OP_VOCABULARY';",
        '  }',
        '  return null;',
        '};',
        '',
        '/**',
        ' * Everything before the first op {@link getRemoteOpBlockReason} would block',
        ' * on. `processRemoteOps` stops at that op, so pre-processing steps (e.g. the',
        ' * full-state conflict gate) must not act on — or prompt the user about —',
        ' * anything from it onwards.',
        ' */',
        'export const takeInterpretableOpPrefix = <',
        "  T extends Pick<Operation, 'opType' | 'syncImportReason'> & { schemaVersion?: unknown },",
        '>(',
        '  ops: readonly T[],',
        '  currentVersion: number = CURRENT_SCHEMA_VERSION,',
        '): T[] => {',
        '  const blockedIndex = ops.findIndex(',
        '    (op) => getRemoteOpBlockReason(op, currentVersion) !== null,',
        '  );',
        '  return blockedIndex === -1 ? [...ops] : ops.slice(0, blockedIndex);',
        '};',
        '',
      ].join('\n'),
    },
  },
} as const;

export const gitBlobSha = (source: string): string =>
  createHash('sha1')
    .update('blob ' + Buffer.byteLength(source, 'utf8') + '\0')
    .update(source, 'utf8')
    .digest('hex');
