// inspired by: https://stackoverflow.com/questions/42155115/how-to-include-git-revision-into-angular-cli-application

const fs = require('fs');
const { execFileSync } = require('child_process');
const gitValue = (args, fallback) => {
  try {
    return execFileSync('git', args, { encoding: 'utf8' }).trim();
  } catch {
    return fallback;
  }
};

const version = process.env.npm_package_version || 'NO_VER';
const revision = process.env.GITHUB_SHA || gitValue(['rev-parse', 'HEAD'], 'NO_REV');
const branch =
  process.env.GITHUB_HEAD_REF ||
  process.env.GITHUB_REF_NAME ||
  gitValue(['rev-parse', '--abbrev-ref', 'HEAD'], 'NO_BRANCH');

const content = `// this file is automatically generated by git.version.ts script
export const versions = {
  version: '${version}',
  revision: '${revision}',
  branch: '${branch}',
};
`;
console.log(`version: '${version}', revision: '${revision}', branch: '${branch}'`);
fs.writeFileSync('src/environments/versions.ts', content, { encoding: 'utf8' });
